### ISSUE TITLE
Negative precipitation is generated by Random Forest, if POE is not specified.

### ISSUE THREAD

**Issue by DaveCasson** [NCAR/GPEP#11]
This issue can be replicated by extending the RF test case (cali2017) to produce ensembles.

If POE is not included, then the result precipitation fields have negative values.

I expect the problem is occuring in the prob_estimate_for_one_var function of probablistic estimation. Without the poe, the first if statement is not met. 

I had tried adding a backtransformation under the perturb_estimates_general function call, but this did not appear to solve the issue.

**Comment by guoqiang-tang** [comment]
Hi Dave, thanks for reporting this issue. I will check the RF ensemble estimation.

**Comment by andywood** [comment]
Thanks -- just to clarify, what does it mean if POE is not included?
Wouldn't POE always be included when generating ensembles?

**Comment by DaveCasson** [comment]
The following settings are required to avoid the issue.

target_vars_WithProbability = [ "prcp",]
probability_thresholds = [ 0,]

Yes, the should be specified.
In my case, building up the ensemble run led to it being missed, and needed to target the cause in the test case.

Without the settings, the negative precip values are produced. I had initially thought it was a lack of back transformation, but based on high precip values still produced, it seems to be a lower cutoff(?).

As the settings should have been specified, you could close on user error. 
But had communicated with Guoqiang, and wanted to raise the issue.

**Comment by guoqiang-tang** [comment]
Thanks for the discussion. The target_vars_WithProbability should be set for variables with occurrence features like precipitation and snow. I'll close this issue
